version: '3.9'

networks:
  web-db-net:

services:
  webserver:
    image: thinhbuzz/php-74-apache-xdebug-29-rewrite
    ports:
      - "80:80"
    volumes:
      - ./mvc:/var/www/html
    restart: "no"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    networks:
      - web-db-net
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    restart: "no"
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: ibb-kw-17-php-pj
    networks:
      - web-db-net

